//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsLedgers
    {
        public long LedgerID { get; set; }
        public string LedgerCode { get; set; }
        public string LedgerName { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<long> SubGroupID { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<long> State { get; set; }
        public Nullable<long> Bank { get; set; }
        public string PanNo { get; set; }
    
        public virtual AccountsGroupOfAccounts AccountsGroupOfAccounts { get; set; }
        public virtual AccountsSubGroupOfAccounts AccountsSubGroupOfAccounts { get; set; }
    }
}
