//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsGroupOfAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountsGroupOfAccounts()
        {
            this.AccountsLedgers = new HashSet<AccountsLedgers>();
            this.AccountsSubGroupOfAccounts = new HashSet<AccountsSubGroupOfAccounts>();
        }
    
        public long GroupID { get; set; }
        public string GroupCode { get; set; }
        public Nullable<long> NatureID { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual AccountsChartsOfAccounts AccountsChartsOfAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsLedgers> AccountsLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsSubGroupOfAccounts> AccountsSubGroupOfAccounts { get; set; }
    }
}
