//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsChartsOfAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountsChartsOfAccounts()
        {
            this.AccountsGroupOfAccounts = new HashSet<AccountsGroupOfAccounts>();
        }
    
        public long NatureID { get; set; }
        public string NatureName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsGroupOfAccounts> AccountsGroupOfAccounts { get; set; }
    }
}
