//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsVoucherType
    {
        public long VoucherID { get; set; }
        public string VoucherTypeName { get; set; }
    }
}
