//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsSubGroupOfAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountsSubGroupOfAccounts()
        {
            this.AccountsLedgers = new HashSet<AccountsLedgers>();
        }
    
        public long SubGroupID { get; set; }
        public string SubGroupCode { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string SubGroupName { get; set; }
    
        public virtual AccountsGroupOfAccounts AccountsGroupOfAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsLedgers> AccountsLedgers { get; set; }
    }
}
