//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMenuMapping
    {
        public long MappingID { get; set; }
        public long UserID { get; set; }
        public long ModuleID { get; set; }
        public Nullable<long> SubmoduleID { get; set; }
        public long MenuID { get; set; }
        public Nullable<long> SubMenuID { get; set; }
        public string Url { get; set; }
    
        public virtual MenuMaster MenuMaster { get; set; }
        public virtual Modules Modules { get; set; }
        public virtual SubMenuMaster SubMenuMaster { get; set; }
        public virtual SubModules SubModules { get; set; }
        public virtual User User { get; set; }
    }
}
